apiVersion: v1
kind: Service
metadata:
    name: whosawthatcoming
    labels:
        name: whosawthatcoming
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3005
      protocol: TCP
    selector:
        name: whosawthatcoming
