Default: &defaults
  user: whosawthatcoming
  password: whosawthatcoming
  host: localhost
  port: 5432
  database: whosawthatcoming
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: whosawthatcoming_test
  <<: *defaults

Staging:
  database: whosawthatcoming_staging
  poolsize: 100
  <<: *defaults

Production:
  database: whosawthatcoming_production
  poolsize: 100
  <<: *defaults
